### ISSUE TITLE
Markers not Disabled and not deleting any markers on map

### ISSUE THREAD

**Issue by berkaslan** [ArmaLife/Framework#792] opened 2016-06-04 21:23 UTC
Hi,

This markers; makes spam errors to client.rpt  
also when players alive or not that shows on map. IF player not alive "Shows Error unit where he/she died."
When I tried to close still shows on map.

**Comment by Jawshy** [comment] 2016-06-05 02:14
Duplicate of [\#365](https://github.com/ArmaLife/Framework/issues/365#issuecomment-218964314). Please search before submitting new issues.

**Closed by Jawshy** 2016-06-05 02:14 UTC
Labels: duplicate
