### ISSUE TITLE
Error in fn_dataQuery.sqf with Enabled HC

### ISSUE THREAD

**Issue by DillGame** [ArmaLife/Framework#603] opened 2016-04-26 13:57 UTC
23:59:40 Error in expression C_isActive) then { [_uid,_side,_sender] remoteExec ["HC_fnc_queryRequest",HC_Lif
23:59:40 Error position: remoteExec ["HC_fnc_queryRequest",HC_Lif
23:59:40 Error Type Bool, expected Number, Side, Object, Group, String
23:59:40 File mpmissions__CUR_MP.Altis\core\session\fn_dataQuery.sqf, line 19

**Comment by BoGuu** [comment] 2016-04-26 14:26
Could you please upload your full RPT log?

**Comment by DillGame** [comment] 2016-04-26 14:33
Client RPT: http://hastebin.com/vaqetomizi.tex

**Comment by BoGuu** [comment] 2016-04-26 15:27
@DillGame 

Can you change this block in life_server/init.sqf:

https://github.com/ArmaLife/Framework/blob/6697e7eac6459348b288f8b3aea9bf860a5d1562/life_server/init.sqf#L24-30

To:

life_HC_isActive = false;
PVAR_ALL("life_HC_isActive");
HC_Life = false;
PVAR_ALL("HC_Life");
if(EQUAL(EXTDB_SETTING(getNumber,"HeadlessMode"),1)) then {
	life_HC_isActive = true;
	PVAR_ALL("life_HC_isActive");
	[] execVM "\life_server\initHC.sqf";
};


And test it again please

**Comment by NiiRoZz** [comment] 2016-04-26 16:53
No if you do that it's fucked up really ....

This error is because you don't have in mission.sqm
HeadlessClient in playable and have name : hc_1

**Comment by BoGuu** [comment] 2016-04-26 17:11
@NiiRoZz 

It's not to do with the mission defined HC AFAIK, it has a different problem.

**Comment by NiiRoZz** [comment] 2016-04-26 18:17
It's that man, it's just that, your changes it's fucked up because he have enabled HC or disabled Hc is the sampe, he just don't put HC inside mission.sqm it's that.

I know what i do, it's me pull HeadlessClient

**Comment by DarkSilencerZA** [comment] 2016-04-27 10:49
@NiiRoZz I don't know what you're talking about.

I have the HC in my sqm and it's named correctly, yet I get the same error.

**Comment by NiiRoZz** [comment] 2016-04-27 10:55
You forcing starter mission ?

**Comment by BoGuu** [comment] 2016-04-27 11:30
It's a deeper problem with how the HC is initialised

**Comment by BoGuu** [comment] 2016-04-28 17:05
@DarkSilencerZA 

Is this still a problem?

**Comment by DarkSilencerZA** [comment] 2016-04-29 15:50
@BoGuu 

I haven't had the time to check.

**Comment by BoGuu** [comment] 2016-04-30 14:16
@DarkSilencerZA 

No problem, when you get the time I'd appreciate some info on it, as I cannot reproduce this.

**Comment by BoGuu** [comment] 2016-05-08 14:12
There has been no further comment to this, and with a fresh build I'm not experiencing it, so on that note, I'm closing it

**Closed by BoGuu** 2016-05-08 14:12 UTC
