### ISSUE TITLE
admin menu - markers can not refresh and disable.

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Framework#718] opened 2016-05-18 14:33 UTC
admin menu - markers can not refresh and disable.

and sometimes marker shows like this : error :when a player was out of channel.::

**Comment by Jawshy** [comment] 2016-05-18 14:38
Duplicate of https://github.com/ArmaLife/Framework/issues/365. Please search before submitting new issues.

**Closed by Jawshy** 2016-05-18 14:38 UTC
