### ISSUE TITLE
[Bug] AAN News Broadcast

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Framework#893] opened 2016-07-25 15:35 UTC
Every now and then, random players complain that the news broadcast gets stuck on their screen and doesn't disappear - and no I do not have any errors in logs for it. Test it, replicate it and fix it. It's a little broken.

**Comment by tkcjesse** [comment] 2016-07-25 15:52
*sigh* ... due to it using LAYERS. I assume this is due to you using my statusBar script. Which depending on how you're using that now and other layers could interfere... I highly doubt this is on vanilla repo....

**Comment by tkcjesse** [comment] 2016-07-25 15:56
https://i.gyazo.com/71c9620f179415cd0d23844ef81d49a3.png

https://i.gyazo.com/f8060103abab29c7fa5b7f77a9211a13.png

**Comment by DarkSilencerZA** [comment] 2016-07-25 18:49
That issue was resolved with the following:

"progressBar" cutRsc ["life_progress","PLAIN"];
"progressBar" cutText ["","PLAIN"];

Layers = retarded.

**Comment by BoGuu** [comment] 2016-07-25 21:17
Still layers, just unique ;)

**Comment by DarkSilencerZA** [comment] 2016-07-26 10:52
For sure, but in such a way that it wouldn't cause an issue.

**Comment by danielstuart14** [comment] 2016-07-26 23:40
Why it was closed if it wasn't fixed in the main repo?
I just came back from vacation and seems like we had a revollution here?
Really?

**Comment by BoGuu** [comment] 2016-07-26 23:45
It's not a bug. Just happens to be the extra status bar he installed causing conflicts

**Comment by trinitynet** [comment] 2016-07-26 23:45
you leave a repo with no directive for a length of time during a time of high activity (APEX) then yes.. people will still do things

**Comment by danielstuart14** [comment] 2016-07-27 00:09
Really? I leaved this repo?
I told I was going on vacation, and I let @BoGuu in charge of all the repo.
Ok ok

**Comment by trinitynet** [comment] 2016-07-27 00:31
"you leave a repo with no directive for a length of time" i knew you was on vacation, please read the whole thing -.-

**Comment by tkcjesse** [comment] 2016-07-27 13:23
@danielstuart14 can you please explain how this is an issue? It wasnt working properly for him because of the layer he was using for a statusbar script. An addon... Whats the issue?

**Closed** 2016-07-27 17:11 UTC
