### ISSUE TITLE
Error in expression - fn_buyHouse

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Framework#675] opened 2016-05-13 07:26 UTC
The following message is written to the client/local RPT log file when a player purchases a house **and** player_advancedLog is set to true: 

```
17:16:05 Error in expression <: %5",profileName,(getPlayerUID player),_gangName,[((_houseCfg select 0))] call >
17:16:05   Error position: <_gangName,[((_houseCfg select 0))] call >
17:16:05   Error Undefined variable in expression: _gangname
17:16:05 File mpmissions\__CUR_MP.Altis\core\housing\fn_buyHouse.sqf, line 44
```

Occurs regardless of whether or not the player is in a gang. 

##### Reproducible: 
- Yes, every time as long as the following is set in [Config_Master](https://github.com/ArmaLife/Framework/blob/3dd4c36b5e13e2332affe5ca9dc5d8f866d7e908/Altis_Life.Altis/Config_Master.hpp) under Data Logging Settings: 
```hpp
    /* Data Logging Settings */
[...]
    player_advancedLog = true; //Logs the following: Houses(purchase/sale), Vehicle(Purchase/Sale/Chopping), Cop Arrests and Gang Creations. SEARCH USING: advanced_log
[...]
```

##### Relevant files: 
- Altis_Life.Altis/core/housing/[fn_buyHouse.sqf](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/core/housing/fn_buyHouse.sqf)

Full RPT files available upon request. 

Game version: [1.58.135742](https://dev.arma3.com/post/spotrep-00055)
Mission version: v4.4r2 as of https://github.com/ArmaLife/Framework/commit/e337b75845ba2b5cf387176ff2ccfcfa9933c20e

**Comment by tkcjesse** [comment] 2016-05-13 07:33
Lmfao. I got it. The issue is simple :p

**Comment by tkcjesse** [comment] 2016-05-13 07:51
Resolved in above ^.

**Closed by tkcjesse** 2016-05-13 07:51 UTC
Labels: bug
